CREATE TABLE "TbUser"(
"UserId" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
"UserName" VARCHAR(255) NOT NULL,
"UserPassword" VARCHAR(255) NOT NULL,
"UserRole" VARCHAR(255) NOT NULL,
"CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"CreatedBy" VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
CONSTRAINT "PK_TbUser" PRIMARY KEY ("UserId")
);

CREATE TABLE "TbSemen"(
"SemenId" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
"SemenName" VARCHAR(255) NOT NULL,
"Price" DECIMAL(18,2) NOT NULL,
"Stock" INT NOT NULL,
"CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"CreatedBy" VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
CONSTRAINT "PK_TbSemen" PRIMARY KEY ("SemenId")
);

CREATE TABLE "TbTransaction"(
"TransactionID" CHAR(20) NOT NULL,
"UserId" INT NOT NULL,
"TransacionDate" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
"CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"CreatedBy" VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
CONSTRAINT "PK_TbTransaction" PRIMARY KEY("TransactionID"),
CONSTRAINT "FK_TbTransaction_TbUser" FOREIGN KEY ("UserId") REFERENCES "TbUser"("UserId")
);

CREATE TABLE "TbTransactionDetail"(
"TransactionDetailId" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
"TransactionID" CHAR(20) NOT NULL,
"UserId" INT NOT NULL,
"SemenId" INT NOT NULL,
"Quantity" INT NOT NULL,
"CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"CreatedBy" VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
CONSTRAINT "PK_TbTransactionDetail" PRIMARY KEY ("TransactionDetailId"),
CONSTRAINT "FK_TbTransactionDetail_TbUser" FOREIGN KEY ("UserId") REFERENCES "TbUser"("UserId"),
CONSTRAINT "FK_TbTransactionDetail_TbSemen" FOREIGN KEY ("SemenId") REFERENCES "TbSemen"("SemenId"),
CONSTRAINT "FK_TbTransactionDetail_TbTransaction" FOREIGN KEY ("TransactionID") REFERENCES "TbTransaction"("TransactionID")
);